#!/usr/bin/env python3
"""Build Bend's curated greenway/path routes from the OSM bike network.

These are the "Casual" hero routes: named, mostly-paved multi-use paths (the
Deschutes River Trail, Discovery Trail, etc.) — distinct from the MTB pane's
singletrack. We collect every network feature sharing a route's name into one
MultiLineString, compute its length + bounds, and emit:

  - src/data/cities/bend/bike-routes.data.ts — import/display metadata

The Bend database seed builds the same MultiLineStrings directly from the bike
network; normalized route coordinates are not checked into Git separately.

Run after scripts/build_bend_bike_network.py (it reads that output).
  python scripts/build_bend_routes.py
"""

from __future__ import annotations

import json
import os

from _geo import M_TO_MI, esc, slugify
from osm_trail_elevation import line_length_m

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
NETWORK = os.path.join(ROOT, "public", "data", "bend", "bike-network.geojson")
OUT_TS = os.path.join(ROOT, "src", "data", "cities", "bend", "bike-routes.data.ts")

# Curated greenway routes: OSM name -> (display name, color, description).
# Names match the `name` tag on OSM ways (collected across all segments). These
# are bidirectional networks assembled from independently digitized OSM ways,
# so they have no canonical traversal direction and must not render arrows.
ROUTES = [
    ("Deschutes River Trail", "Deschutes River Trail", "#2563EB",
     "Bend's signature riverside path — mostly paved, linking the Old Mill, "
     "downtown, and the river parks."),
    ("Discovery Trail", "Discovery Trail", "#059669",
     "Paved path winding through Bend's west-side neighborhoods and parks."),
    ("Rimrock Trail", "Rimrock Trail", "#7C3AED",
     "Paved path along the canyon rim on the northeast side."),
    ("Haul Road Trail", "Haul Road Trail", "#F97316",
     "Paved rail-trail-style path on the south side of town."),
    ("Larkspur Trail", "Larkspur Trail", "#DB2777",
     "Paved path connecting the Larkspur area toward Pilot Butte."),
    ("Cascade Highlands Trail", "Cascade Highlands Trail", "#0891B2",
     "Paved path through the Cascade Highlands on the southwest edge."),
    ("Tumalo Creek Trail", "Tumalo Creek Trail", "#65A30D",
     "Paved path tracing Tumalo Creek on the west side."),
    ("West Bend Trail", "West Bend Trail", "#CA8A04",
     "Paved path through the West Bend / Shevlin area."),
]

DEFAULT_WIDTH = 8


def line_len_mi(coords) -> float:
    return line_length_m(coords) * M_TO_MI


def main():
    with open(NETWORK, encoding="utf-8") as fh:
        net = json.load(fh)

    by_name: dict[str, list] = {}
    for f in net["features"]:
        nm = f["properties"].get("name")
        if nm:
            by_name.setdefault(nm, []).append(f["geometry"]["coordinates"])

    ts_entries = []
    missing = []
    for osm_name, display, color, desc in ROUTES:
        segs = by_name.get(osm_name)
        if not segs:
            missing.append(osm_name)
            continue
        rid = slugify(display)
        dist = round(sum(line_len_mi(s) for s in segs), 1)
        xs = [p[0] for s in segs for p in s]
        ys = [p[1] for s in segs for p in s]
        bounds = [round(min(xs), 6), round(min(ys), 6),
                  round(max(xs), 6), round(max(ys), 6)]
        ts_entries.append({
            "id": rid, "name": display, "color": color,
            "description": desc, "distance": dist, "bounds": bounds,
            "kind": "trail" if display == "Deschutes River Trail" else "path",
        })

    if missing:
        print(f"WARNING: no network features for: {missing}")

    write_ts(ts_entries)
    print(f"Wrote {len(ts_entries)} entries -> {OUT_TS}")
    for e in ts_entries:
        print(f"  {e['name']:26s} {e['distance']:5.1f} mi")


def write_ts(entries):
    lines = [
        "import { faRoute } from '@fortawesome/free-solid-svg-icons';",
        "import type { BikeRoute } from '@/data/bike-routes';",
        "",
        "// Generated by scripts/build_bend_routes.py from the OSM bike network.",
        "// The Bend seed builds geometry from public/data/bend/bike-network.geojson;",
        "// these entries carry the import/display metadata. Do not edit by hand.",
        "",
        "export const bendBikeRoutes: BikeRoute[] = [",
    ]
    for e in entries:
        b = ", ".join(str(x) for x in e["bounds"])
        lines += [
            "  {",
            f"    id: '{esc(e['id'])}',",
            f"    name: '{esc(e['name'])}',",
            f"    color: '{e['color']}',",
            f"    description: '{esc(e['description'])}',",
            "    icon: faRoute,",
            f"    defaultWidth: {DEFAULT_WIDTH},",
            "    opacity: 1.0,",
            f"    kind: '{e['kind']}',",
            "    hideArrows: true,",
            f"    distance: {e['distance']},",
            f"    defaultBounds: [{b}],",
            "  },",
        ]
    lines += ["];", ""]
    with open(OUT_TS, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


if __name__ == "__main__":
    main()
