import { describe, expect, it } from 'vitest';
import {
  CLOSE_MARKER,
  OPEN_MARKER,
  extractSection,
  spliceSection,
} from './pr-section';

describe('spliceSection', () => {
  it('appends a summary to a description without markers', () => {
    const body = spliceSection(
      '## Summary\n- Adds a layer',
      'What it is.',
      meta,
    );
    expect(body.startsWith('## Summary\n- Adds a layer\n\n')).toBe(true);
    expect(body).toContain(OPEN_MARKER);
    expect(body).toContain('🤖\n_Generated by Claude for abcdef1.');
    expect(extractSection(body)).toContain('What it is.');
  });

  it('handles an empty description', () => {
    const body = spliceSection(null, 'What it is.', meta);
    expect(body.startsWith(OPEN_MARKER)).toBe(true);
  });

  it('replaces only the text between the markers', () => {
    const first = spliceSection('Intro', 'Old summary.', meta);
    const next = spliceSection(`${first}\nTrailing note`, 'New summary.', meta);
    expect(next.startsWith('Intro\n\n')).toBe(true);
    expect(next.endsWith('\nTrailing note')).toBe(true);
    expect(next).not.toContain('Old summary.');
    expect(countMarkers(next)).toBe(1);
  });

  it('ignores markers mentioned mid-line', () => {
    const body = `The bot writes between \`${OPEN_MARKER}\` and \`${CLOSE_MARKER}\`.`;
    expect(extractSection(body)).toBe('');
    expect(spliceSection(body, 'Summary.', meta).startsWith(body)).toBe(true);
  });

  it('matches markers saved with CRLF line endings', () => {
    const body = `Intro\r\n${OPEN_MARKER}\r\nold\r\n${CLOSE_MARKER}\r\n`;
    const next = spliceSection(body, 'New.', meta);
    expect(next).not.toContain('old');
    expect(countMarkers(next)).toBe(1);
  });

  it("refuses to exceed GitHub's description limit", () => {
    expect(() => spliceSection('x'.repeat(64000), 'Summary.', meta)).toThrow(
      /limit/,
    );
  });
});

function countMarkers(body: string): number {
  return body.split(OPEN_MARKER).length - 1;
}

const meta = {
  headSha: 'abcdef1234567890',
  runUrl: 'https://github.com/o/r/actions/runs/1',
};
