import { faRoute } from '@fortawesome/free-solid-svg-icons';
import type { BikeRoute } from '@/data/bike-routes';

// Generated by scripts/build_bend_routes.py from the OSM bike network.
// Geometry lives in public/data/bend/routes.geojson (matched by `id`);
// these entries carry the display metadata. Do not edit by hand.

export const bendBikeRoutes: BikeRoute[] = [
  {
    id: 'deschutes-river-trail',
    name: 'Deschutes River Trail',
    color: '#2563EB',
    description:
      "Bend's signature riverside path — mostly paved, linking the Old Mill, downtown, and the river parks.",
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 13.2,
    defaultBounds: [-121.43481, 43.94791, -121.30986, 44.07613],
  },
  {
    id: 'discovery-trail',
    name: 'Discovery Trail',
    color: '#059669',
    description:
      "Paved path winding through Bend's west-side neighborhoods and parks.",
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 4.1,
    defaultBounds: [-121.37443, 44.02321, -121.35834, 44.08177],
  },
  {
    id: 'rimrock-trail',
    name: 'Rimrock Trail',
    color: '#7C3AED',
    description: 'Paved path along the canyon rim on the northeast side.',
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 3.2,
    defaultBounds: [-121.40512, 43.99755, -121.36397, 44.02192],
  },
  {
    id: 'haul-road-trail',
    name: 'Haul Road Trail',
    color: '#F97316',
    description: 'Paved rail-trail-style path on the south side of town.',
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 3.7,
    defaultBounds: [-121.36397, 44.02192, -121.32113, 44.04824],
  },
  {
    id: 'larkspur-trail',
    name: 'Larkspur Trail',
    color: '#DB2777',
    description: 'Paved path connecting the Larkspur area toward Pilot Butte.',
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 2.4,
    defaultBounds: [-121.28429, 44.03842, -121.27687, 44.06571],
  },
  {
    id: 'cascade-highlands-trail',
    name: 'Cascade Highlands Trail',
    color: '#0891B2',
    description:
      'Paved path through the Cascade Highlands on the southwest edge.',
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 1.7,
    defaultBounds: [-121.36066, 44.05049, -121.3388, 44.05672],
  },
  {
    id: 'tumalo-creek-trail',
    name: 'Tumalo Creek Trail',
    color: '#65A30D',
    description: 'Paved path tracing Tumalo Creek on the west side.',
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 1.4,
    defaultBounds: [-121.40035, 44.05821, -121.38288, 44.07345],
  },
  {
    id: 'west-bend-trail',
    name: 'West Bend Trail',
    color: '#CA8A04',
    description: 'Paved path through the West Bend / Shevlin area.',
    icon: faRoute,
    defaultWidth: 8,
    opacity: 1.0,
    distance: 1.4,
    defaultBounds: [-121.36369, 44.05273, -121.33892, 44.05806],
  },
];
