/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    trails: Trail;
    'trail-areas': TrailArea;
    organizations: Organization;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    trails: TrailsSelect<false> | TrailsSelect<true>;
    'trail-areas': TrailAreasSelect<false> | TrailAreasSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    theme: Theme;
  };
  globalsSelect: {
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trails".
 */
export interface Trail {
  id: number;
  /**
   * Human-friendly name shown in the sidebar and pane.
   */
  displayName: string;
  city: 'chattanooga' | 'bend';
  /**
   * The raw `Trail` property value from the Mapbox tileset. This is the join key to rendered features — change it only if the upstream GIS data changed.
   */
  trailName: string;
  /**
   * Canonical slug when it differs from the trail name. Also names the elevation profile JSON.
   */
  slug?: string | null;
  /**
   * Who builds and maintains this trail. Manage the list under Map content → Organizations.
   */
  organization?: (number | null) | Organization;
  /**
   * Manage the list under Map content → Trail complexes.
   */
  area: number | TrailArea;
  rating: 'easy' | 'intermediate' | 'advanced' | 'expert' | 'unrated';
  /**
   * Drives the line color and marker icon. Colors are derived from kind + rating rather than stored, so a palette change is one code edit.
   */
  kind: 'trail' | 'greenway';
  /**
   * The OSM ways this trail rides on. Pick them on the map — everything below is rebuilt from them when you save.
   */
  osmIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Imported trails keep whatever geometry and measurements came with them; the OSM rebuild leaves them alone. Set this to OSM once the trail has been matched to way ids.
   */
  geometrySource: 'osm' | 'imported';
  /**
   * Rebuild from OSM on the next save even if the ways have not changed. Use after a trail has been rerouted or fixed upstream.
   */
  rebuildGeometry?: boolean | null;
  osmReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Miles, measured from the OSM geometry.
   */
  distance?: number | null;
  /**
   * Feet, sampled from Mapbox Terrain-RGB.
   */
  elevationGain?: number | null;
  elevationLoss?: number | null;
  elevationMin?: number | null;
  elevationMax?: number | null;
  /**
   * [swLng, swLat, neLng, neLat], for zoom-to-fit.
   */
  bounds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * GeoJSON MultiLineString (EPSG:4326) assembled from the OSM ways. A cache of what OSM says, not a source of truth.
   */
  geom?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The clubs and agencies that maintain trails. Anything added here becomes selectable on a trail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  /**
   * Full name, e.g. "Central Oregon Trail Alliance".
   */
  name: string;
  /**
   * e.g. "COTA". Shown where space is tight.
   */
  abbreviation?: string | null;
  city?: ('chattanooga' | 'bend') | null;
  /**
   * Where riders can find them — membership, trail reports.
   */
  url?: string | null;
  /**
   * A sentence or two. Optional.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trail complexes trails are grouped under, and the region each sits in. Anything added here becomes selectable on a trail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-areas".
 */
export interface TrailArea {
  id: number;
  /**
   * As shown in the sidebar, e.g. "Phil's Trail Complex".
   */
  name: string;
  city: 'chattanooga' | 'bend';
  /**
   * The heading this complex sits under in the sidebar — the level above it, e.g. "Bend" or "Cascade Lakes". Leave blank to use the built-in mapping.
   */
  region?: string | null;
  /**
   * Optional.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  /**
   * Which city this editor can change. Ignored for admins, who can edit every city.
   */
  city?: ('chattanooga' | 'bend') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'trails';
        value: number | Trail;
      } | null)
    | ({
        relationTo: 'trail-areas';
        value: number | TrailArea;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trails_select".
 */
export interface TrailsSelect<T extends boolean = true> {
  displayName?: T;
  city?: T;
  trailName?: T;
  slug?: T;
  organization?: T;
  area?: T;
  rating?: T;
  kind?: T;
  osmIds?: T;
  geometrySource?: T;
  rebuildGeometry?: T;
  osmReport?: T;
  distance?: T;
  elevationGain?: T;
  elevationLoss?: T;
  elevationMin?: T;
  elevationMax?: T;
  bounds?: T;
  geom?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-areas_select".
 */
export interface TrailAreasSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  region?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  abbreviation?: T;
  city?: T;
  url?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * How the admin looks. Changes apply on the next page load. Clear a field to fall back to the default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Focus rings and highlights. Default #c3f44d.
   */
  accentColor?: string | null;
  /**
   * Deep brand colour. Default #1a434e.
   */
  deepColor?: string | null;
  /**
   * The cast of the greys everything is built from. Applies to both light and dark mode, because Payload derives dark mode by inverting the same scale.
   */
  neutralTint?: ('cool' | 'neutral' | 'warm') | null;
  cornerStyle?: ('sharp' | 'soft' | 'round') | null;
  fontFamily?: ('geist' | 'system' | 'serif') | null;
  /**
   * Escape hatch for anything the fields above do not cover. Injected verbatim into the admin. Admins only — treat it as code.
   */
  customCss?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  accentColor?: T;
  deepColor?: T;
  neutralTint?: T;
  cornerStyle?: T;
  fontFamily?: T;
  customCss?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}